
SET NOCOUNT ON
INSERT INTO Paises
([Nombre])
VALUES
 ('Alemania')
,('Argentina')
,('Australia')
,('Austria')
,('Bélgica')
,('Bolivia')
,('Brasil')
,('Canadá')
,('Chile')
,('China')
,('Colombia')
,('Corea')
,('Costa Rica')
,('Cuba')
,('Dinamarca')
,('Ecuador')
,('El Salvador')
,('España')
,('Estados Unidos')
,('Francia')
,('Grecia')
,('Guatemala')
,('Haití')
,('Holanda')
,('Honduras')
,('Hungría')
,('Irlanda')
,('Israel')
,('Italia')
,('Japón')
,('Líbano')
,('México')
,('Nicaragua')
,('Noruega')
,('Panamá')
,('Paraguay')
,('Perú')
,('Polonia')
,('Portugal')
,('Gran Bretaña')
,('Rep. Dominicana')
,('Rumania')
,('Siria')
,('Suecia')
,('Suiza')
,('Turquía')
,('Uruguay')
,('Venezuela')
,('Puerto Rico')
,('Otros países de América')
,('Otros países europeos')
,('Otros países asiáticos')
,('Unión Sudafricana')
,('Otros países de Africa')
,('Otros países de Oceanía')
,('Apátrida')
